In [ ]:
#CREATING A np ARRAY

import numpy as np
array1 = np.array([1,2,3,4,5])
print(array1)

[1 2 3 4 5]


In [ ]:
#IDENTIFYING THE SIZE OF THE LIST AND np list:
import sys

#IDENTIFYING IN LIST:
lst=range(100)
print("size of each element in lst:",sys.getsizeof(lst))
print("size of lst: ",sys.getsizeof(lst)*len(lst))

#IDENTIFYING IN np:
nplst=np.arange(100)
print("size of each element in nplst:", nplst.itemsize)
print("size of nplst:", nplst.size*nplst.itemsize)

size of each element in lst: 48
size of lst:  4800
size of each element in nplst: 4
size of nplst: 400


In [ ]:
#CREATING np ARRAY OF ZEROS:

arr0 = np.zeros((2,2))
print(arr0)

#ZERO ARRAY AS INT DATA TYPE:
print(np.int16(arr0))

[[0. 0.]
 [0. 0.]]
[[0 0]
 [0 0]]


In [ ]:
#CREATING AN ARRAY OF A NUMBER:
numarr=np.ones(10)
print(numarr)
print(np.int16(numarr))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


In [ ]:
#CREATING AN IDENTITY MATRIX:

identitymatrix = np.eye(3)
print(identitymatrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#GETTING THE DATATYPE OF A npARRAY:

arr1= np.array(np.int16([2,4,6,8,10]))
print(arr1.dtype)

arr2 = np.array([1,2,3,4,5])
print(arr2.dtype)

int16
int32


In [ ]:
#USING ARITHMATIC OPERATIONS:

import numpy as np

a = np.array([1, 2, 3, 4])
b=np.array([5, 6, 7, 8])
print(a + b)
print(a-b)
print(a*b)
print(a/b)
print(a ** b)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [ ]:
#SLICING:

x = np.arange (10)
print("x= ",x)
print("\n x[:5]= ",x[:5])
print("\n x[5:]= ",x[5:])
print("\n x[4:7]= ",x[4:7])
print("\n x[::2]= ",x[::2])
print("\n x[1::2]= ",x[1::2])
print("\n x[::-1]= ",x[::-1])
print("\n x[5::-2]= ",x [5::-2])

x=  [0 1 2 3 4 5 6 7 8 9]

 x[:5]=  [0 1 2 3 4]

 x[5:]=  [5 6 7 8 9]

 x[4:7]=  [4 5 6]

 x[::2]=  [0 2 4 6 8]

 x[1::2]=  [1 3 5 7 9]

 x[::-1]=  [9 8 7 6 5 4 3 2 1 0]

 x[5::-2]=  [5 3 1]


In [ ]:
#BOOLEAN EXPRESSION IN NUMPY

import numpy as np

a= np.arange(12).reshape(3,4)
print("a = ",a)
print("\n")
b = a > 4
print("b = ", b)
print("\n")
print("a [b]= ", a [b]) # 1d array
print("\n")
a [b] = 1
print("a= ",a)

a =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


b =  [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


a [b]=  [ 5  6  7  8  9 10 11]


a=  [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [ ]:
#OBTAINING DATAS FROM NUMPY ARRAY USING STRINGS AND BOOLEAN
names = np.array(['Bat', 'cat', 'Dog', 'Bat', 'Dog', 'cat', 'Dog'])
data= np.arange(20).reshape(5, 4)
print(names)
print("data = ", data)
print("\n")
print("names bool = ", names == 'Bat')
print("\n")
print("names == 'Bat' ", data [names == 'Bat'])
print("\n")
print("names == 'cat', 2: ", data [names == 'cat', 2:])
print("\n")
print("names == 'Dog',3: ", data [names == 'Dog', 3])

['Bat' 'cat' 'Dog' 'Bat' 'Dog' 'cat' 'Dog']
data =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


names bool =  [ True False False  True False False False]




IndexError: boolean index did not match indexed array along axis 0; size of axis is 5 but size of corresponding boolean axis is 7